{{- if and (.Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1") (eq .Values.PAAS_PLATFORM "KUBERNETES") -}}
{{ if and .Values.powaUI.install .Values.tls.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: powa-ui-frontend-redirect
spec:
  parentRefs:
  - name: {{ .Values.powaUI.ingress.gatewayName | default "default-external-gateway" }}
    namespace: {{ .Values.powaUI.ingress.envoyNamespace | default "envoy-gateway" }}
    port: 80
  hostnames: [{{ .Values.powaUI.ingress.host  | quote }}]
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
{{- end }}
{{- end }}