name: Add License Header
on:
  push:
    branches:
      - 'main'
env:
   COPYRIGHT_COMPANY: 'NetCracker Technology Corporation'
   COPYRIGHT_YEAR: '2024-2025'
jobs:
  license:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          find . -type f \( -name "*.go" -o -name "*.sh" -o -name "*.py" \) -print0 | \
          xargs -0 docker run -v "${PWD}:/src" -i ghcr.io/google/addlicense \
          -v -c "${{ env.COPYRIGHT_COMPANY }}" -y "${{ env.COPYRIGHT_YEAR }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          commit-message: Auto-update license header
          branch: license-update
          title: Add License Header
          body: Automated license header update
          delete-branch: true
